name: GuppyCosmetics
version: '1.1.0-ALPHA'
main: com.tenshiku.guppycosmetics.GuppyCosmetics
api-version: '1.21'
author: tenshiku
commands:
  guppycosmetics:
    description: Main command for GuppyCosmetics plugin.
    usage: /<command> <spawn|give|reload>
    aliases: [gc]
permissions:
  guppycosmetics.spawn:
    description: Allows spawning cosmetic items for yourself
    default: op
  guppycosmetics.give:
    description: Allows giving cosmetic items to other players
    default: op
  guppycosmetics.reload:
    description: Allows reloading the plugin configuration
    default: op