name: GuppyCosmetics
version: '1.0.0-ALPHA'
main: com.tenshiku.guppycosmetics.GuppyCosmetics
api-version: '1.21'
author: tenshiku
commands:
  guppycosmetics:
    description: Main command for GuppyCosmetics plugin.
    usage: /<command> <spawn|reload>
    aliases: [gc]